apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: saga-loan-demo  
  name: loan-demo-database
  namespace: saga-loan-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: loan-demo-database
  strategy:
      type: Recreate
  template:
    metadata:
      labels: 
        app.kubernetes.io/name: loan-demo-database
      name: loan-demo-database
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: loan-demo-database
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: loan-demo-database
        - name: POSTGRES_DATABASE
          valueFrom:
            secretKeyRef:
              key: database-name
              name: loan-demo-database
        - name: PGDATA
          valueFrom:
            secretKeyRef:
              key: database-data
              name: loan-demo-database
        image: quay.io/abryson/postgresql-amd64-alpine:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - '/usr/local/bin/pg_isready -U "postgres" -h 127.0.0.1 -p 5432'
          initialDelaySeconds: 120
          timeoutSeconds: 10
        name: postgresql
        ports:
        - containerPort: 5432
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - '/usr/local/bin/pg_isready -U "postgres" -h 127.0.0.1 -p 5432'
          initialDelaySeconds: 15
          timeoutSeconds: 2
        resources:
          limits:
            memory: 2Gi
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: "/temp/data"
          name: loan-demo-database-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: loan-demo-database-data
        persistentVolumeClaim:
          claimName: loan-demo-database